### ISSUE TITLE
Automate docs deployment

### ISSUE THREAD

**Issue by drewbo** [sat-utils/sat-api-express#3]

**Comment by matthewhanson** [comment]
@drewbo docs are on the gh-pages branch, doesn't that autodeploy already ?

Are these docs created from the js code here?  What would be needed to move this into the sat-api repo so we can deprecate this?

**Comment by drewbo** [comment]
Yeah, this is automated via 0477d696b0284f7f7e1ec66f4d2b57a8d125eba8

It uses [`apidoc`](https://www.npmjs.com/package/apidoc) to generate the docs from all the [express endpoint docstrings](https://github.com/sat-utils/sat-api-express/blob/master/app/index.js#L41-L225)
